# Generated by Django 2.1.3 on 2018-11-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20181128_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=30, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frombankaccount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frombankaccount', to='accounts.BankAccount')),
                ('tobankaccount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tobankaccount', to='accounts.BankAccount')),
            ],
        ),
    ]
