# Generated by Django 2.1.3 on 2018-11-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='frombankaccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frombankaccount', to='accounts.BankAccount'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='tobankaccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tobankaccount', to='accounts.BankAccount'),
        ),
    ]
