# Generated by Django 2.1.3 on 2018-11-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20181128_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='number',
            field=models.CharField(default=None, max_length=30, null=True, unique=True),
        ),
    ]
