# Generated by Django 2.1.3 on 2018-11-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20181128_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='number',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
