# Generated by Django 2.1.3 on 2018-11-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20181128_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
