# Generated by Django 2.1.3 on 2018-11-28 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20181128_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='frombankaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frombankaccount', to='accounts.BankAccount'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='tobankaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tobankaccount', to='accounts.BankAccount'),
        ),
    ]
