# Generated by Django 2.1.3 on 2018-11-28 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_transactionlog_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
