# Generated by Django 2.1.3 on 2018-11-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181128_0756'),
        ('bank', '0013_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='number',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favbankaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favbankaccount', to='accounts.BankAccount'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='bankaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount', to='accounts.BankAccount'),
        ),
    ]
