# Generated by Django 2.1.3 on 2018-11-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20181129_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='bankaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='accounts.BankAccount'),
        ),
    ]
