# Generated by Django 2.1.3 on 2018-11-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181128_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
